import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Role = "admin" | "supervisor" | "viewer";
type Call = { id: string; originalCaller?: string; fromNumber?: string; provider: "twilio" | "telnyx"; status: string; startedAt: string; aiState?: string; costUsd?: number };
type Transcript = { id: string; speaker: "caller" | "assistant" | "operator"; text: string; source: string; occurredAt: string };
type Me = { user: { id: string; email: string; role: Role } | null; csrfToken?: string };
const api = async (path: string, init: RequestInit = {}) => { const response = await fetch(path, { credentials: "same-origin", headers: { "content-type": "application/json", ...(init.headers ?? {}) }, ...init }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Request failed"); return json; };

function Login({ onLogin }: { onLogin: (me: Me) => void }) { const [email, setEmail] = useState("admin@example.ca"); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <main className="login"><section><p className="eyebrow">COOPER2TALK</p><h1>Operator console</h1><p>Secure, live oversight for your AI receptionist.</p><form onSubmit={async (e) => { e.preventDefault(); try { setError(""); onLogin(await api("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) })); } catch (err) { setError((err as Error).message); } }}><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" /></label><label>Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" /></label>{error && <p className="error">{error}</p>}<button>Sign in</button></form></section></main>; }

function App() {
  const [me, setMe] = useState<Me>({ user: null }); const [calls, setCalls] = useState<Call[]>([]); const [selected, setSelected] = useState<Call | null>(null); const [transcript, setTranscript] = useState<Transcript[]>([]); const [instruction, setInstruction] = useState(""); const [notice, setNotice] = useState("");
  const canIntervene = me.user?.role === "admin" || me.user?.role === "supervisor";
  useEffect(() => { api("/api/me").then(setMe).catch(() => undefined); }, []);
  useEffect(() => { if (!me.user) return; api("/api/calls").then((r) => setCalls(r.calls)); const socket = new WebSocket(`${location.protocol === "https:" ? "wss" : "ws"}://${location.host}/ws`); socket.onmessage = (e) => { const { event, payload } = JSON.parse(e.data); if (event === "call.started") setCalls((current) => [payload, ...current.filter((c) => c.id !== payload.id)]); if (event === "call.updated") setCalls((current) => [payload, ...current.filter((c) => c.id !== payload.id)]); if (event === "transcript.message" && selected?.id === payload.callId) setTranscript((current) => [...current, payload]); if (event === "injection.status") setNotice(`Instruction ${payload.status}`); }; return () => socket.close(); }, [me.user, selected?.id]);
  const openCall = async (call: Call) => { const data = await api(`/api/calls/${call.id}`); setSelected(data.call); setTranscript(data.transcript); setNotice(""); };
  const submitInstruction = async () => { if (!selected || !instruction.trim()) return; try { const response = await api(`/api/calls/${selected.id}/injections`, { method: "POST", headers: { "x-csrf-token": me.csrfToken ?? "" }, body: JSON.stringify({ text: instruction }) }); setInstruction(""); setNotice(`Instruction queued: ${response.instructionId.slice(0, 8)}`); } catch (error) { setNotice((error as Error).message); } };
  if (!me.user) return <Login onLogin={setMe} />;
  return <main className="shell"><aside><div><p className="eyebrow">COOPER2TALK</p><h2>Live calls</h2></div><div className="user">{me.user.email}<small>{me.user.role}</small></div><nav>{calls.map((call) => <button className={`call ${selected?.id === call.id ? "active" : ""}`} key={call.id} onClick={() => void openCall(call)}><strong>{call.originalCaller ?? call.fromNumber ?? "Unknown caller"}</strong><span>{call.provider} · {call.status} · {new Date(call.startedAt).toLocaleTimeString()}</span></button>)}{calls.length === 0 && <p className="empty">No calls yet. Dograh events will appear here.</p>}</nav></aside><section className="content">{selected ? <><header><div><p className="eyebrow">ACTIVE CALL</p><h1>{selected.originalCaller ?? selected.fromNumber ?? "Unknown caller"}</h1><p>{selected.provider} · {selected.status} · AI {selected.aiState ?? "listening"}</p></div><div className="badge">Transcript only</div></header><section className="transcript">{transcript.map((line) => <article className={line.speaker} key={line.id}><strong>{line.speaker === "caller" ? "Caller" : line.speaker === "assistant" ? "AI" : "Operator"}</strong><p>{line.text}</p><small>{new Date(line.occurredAt).toLocaleTimeString()} · {line.source}</small></article>)}{transcript.length === 0 && <p className="empty">Waiting for the first transcript turn…</p>}</section>{canIntervene && <section className="inject"><label>Operator instruction<textarea value={instruction} onChange={(e) => setInstruction(e.target.value)} placeholder="Tell them we are closing at 4 PM due to an emergency." /></label><div><button onClick={() => void submitInstruction()}>Interrupt and update AI</button>{notice && <span>{notice}</span>}</div></section>}</> : <section className="welcome"><p className="eyebrow">READY</p><h1>Select a call to inspect it live.</h1><p>WhatsApp replies are processed through the same secure intervention service.</p></section>}</section></main>;
}
createRoot(document.getElementById("root")!).render(<App />);
